version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: brevly-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: brevly
    volumes:
      - pgdata:/var/lib/postgresql/data

  brevly-server:
    image: isabellareis/brevly-server:latest
    container_name: brevly-server
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      NODE_ENV: development
      DATABASE_URL: postgresql://docker:docker@postgres:5432/brevly
      CLOUDFLARE_ACCOUNT_ID: ""
      CLOUDFLARE_ACCESS_KEY_ID: ""
      CLOUDFLARE_SECRET_ACCESS_KEY: ""
      CLOUDFLARE_BUCKET: "upload-server"
      CLOUDFLARE_PUBLIC_URL: "https://pub-#.r2.dev"
      SHORT_LINK_DOMAIN: http://localhost:3333

volumes:
  pgdata:
